CREATE SEQUENCE user_id_seq;
CREATE TABLE APPLICATION_USER (
  ID         NUMERIC PRIMARY KEY DEFAULT nextval('user_id_seq'),
  USERNAME   VARCHAR(255) NOT NULL UNIQUE,
  EMAIL      VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD   VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME  VARCHAR(255) NOT NULL
);

CREATE SEQUENCE role_id_seq;
CREATE TABLE ROLE (
  ID   NUMERIC PRIMARY KEY DEFAULT nextval('role_id_seq'),
  ROLE VARCHAR(255)
);

CREATE TABLE USER_ROLE (
  USER_ID NUMERIC REFERENCES APPLICATION_USER (ID),
  ROLE_ID NUMERIC REFERENCES ROLE (ID)
);

INSERT INTO role (role) VALUES ('USER');
INSERT INTO role (role) VALUES ('ADMIN');


CREATE SEQUENCE task_id_seq;
CREATE TABLE Task (
  ID          NUMERIC PRIMARY KEY DEFAULT nextval('task_id_seq'),
  TASK_NAME   VARCHAR(255),
  TASK_STATUS VARCHAR(255),
  TASK_TYPE   VARCHAR(255),
  USER_ID     NUMERIC REFERENCES APPLICATION_USER (ID)
);